config/routes.rb
Rails.application.routes.draw do

  get 'clubs/index'
  get 'clubs/new'
  get 'clubs/edit'
  get 'clubs/show'
  
  root :to => 'pages#home' # for home page
  
  resources :users
  resources :clubs
  resources :players
  
  get 'national_teams/edit', to: 'national_teams#edit', as: :edit_national_teams
  get 'national_teams/editteam/:id', to: 'national_teams#editteam', as: :edit_national_team #custom link

  resources :national_teams
  
  get 'clubs/editclub/:id', to: 'clubs#editclub', as: :editclub_club #custom link

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :players
end

app/models/national_team.rb
class NationalTeam < ApplicationRecord
    has_many :players
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :club
    belongs_to :national_team, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password #virtal attributes that will run throug the bcript..? password_confirmation
    validates :email, :uniqueness => true, :presence => true
    # validates :password, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :fetch_user

    private
    def fetch_user
        #copy and paste it when ever if you have to do a login page

        @current_user = User.find_by :id => session[:user_id] # Will Not throw an error
        # @current_user = User.find_by session[:user_id] # Willthrow an error
        session[:user_id] = nil unless @current_user.present? #log out non existent user -

    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to clubs_index_path unless (@current_user.present? && @current_user.admin?)
    end
    
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :check_for_admin, :only => [:edit, :new]
  def index
    @clubs = Club.all.order(:name)
  end

  def new
    @club = Club.new
  end

  def create
    club = Club.create club_params
    redirect_to club #change later to add new player page
  end

  def show
    @club = Club.find params[:id]
    @players = @club.players

  end

  def edit
    @clubs = Club.all.order(:name)
  end

  def editclub
    @club = Club.find(params[:id])
  end
  
  def update
    club = Club.find params[:id]
    club.update club_params
    redirect_to club
  end

  def destroy
    club = Club.find params[:id]
    club.destroy
    redirect_to clubs_path
  end

  private
  def club_params
    #anything in a form should be permitted here
    params.required(:club).permit(:name, :location, :titles_won, :stadium_cap, :logo, :current_manager)
  end

end

app/controllers/national_teams_controller.rb
class NationalTeamsController < ApplicationController
  before_action :check_for_admin, :only => [:edit, :new]

  def index
    @national_teams = NationalTeam.all.order(:name)

  end

  def new 
    @national_team = NationalTeam.new
  end

  def create 
    national_team = NationalTeam.create national_team_params
    redirect_to national_team #redirect to players?

  end

  def show
    @national_team = NationalTeam.find(params[:id])
    @players = @national_team.players
  end


  def edit
    @national_teams = NationalTeam.all.order(:name)
  end

  def editteam
    @national_team = NationalTeam.find params[:id]

  end

  def update
    national_team = NationalTeam.find params[:id]
    national_team.update national_team_params
    redirect_to national_team

  end

  def destroy
    national_team = NationalTeam.find params[:id]
    national_team.destroy
    redirect_to national_teams_path
  end

  private
  def national_team_params

    params.required(:national_team).permit(:name, :coach, :cups_won, :logo)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def show
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :check_for_admin, :only => [:edit, :new]
  
  def index
    @players = Player.all.order(:name)
  end

  def show
    @player = Player.find params[:id]
    @nationalteam = @player.national_team
  end

  def new
    @player = Player.new
  end

  def create
    player = Player.create player_params
    redirect_to player
  end

  def edit
    @player = Player.find params[:id]
  end

  def update
    player = Player.find params[:id]
    player.update player_params
    redirect_to player
  end

  def destroy
    player = Player.find params[:id]
    player.destroy
    redirect_to players_path
  end
  
  private
  def player_params
    params.required(:player).permit(:name, :position, :career_goals, :appearances, :dob, :image, :club_id, :national_team_id)
  end

end


# t.integer "club_id"
# t.integer "national_team_id"

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      # redirect_to root_path - - - - - - - --  - 
      redirect_to clubs_index_path

    else
      # @error = "Invalid user name or password" wrong way of doing it and display it new.html.erb sessiaoin
      flash[:error] = "Invalid username or password" #same as saying session[:error] = "" but it will disappear in the next page
 
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :check_for_admin, :only => [:edit, :new]
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
          session[:user_id] = @user.id #user should be taken to login page
          # redirect_to root_path #change the path aftger user logs in 
          redirect_to clubs_index_path
        else
          render :new 
        end

      end
    
      private
      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/national_teams_helper.rb
module NationalTeamsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clubs/_form.html.erb
<div class="p-5">
<%= form_for @club do |f| %>
    <div class="mb-3">
     <%= f.label :name, :class => 'form-label ' %>
    <%= f.text_field :name, :class =>"form-control", :required => true %>
    </div>

    <div class="mb-3">
    <%= f.label :location, :class => 'form-label' %>
    <%= f.text_field :location, :class => 'form-control' %>
    </div>
    

    <%= f.label :logo, 'Club Logo', :class => 'form-label'  %>
    <%= f.url_field :logo, :placeholder => 'URL', :class => 'form-control' %>
    
    <div class="mt-5">
    <%= f.label :titles_won, :class => 'form-label' %>
    <%= f.text_field :titles_won, :class => 'form-control-sm me-4' %>

    <%= f.label :stadium_cap, 'Stadium Capacity', :class => 'form-label' %>
    <%= f.text_field :stadium_cap, :class => 'form-control-sm  me-4' %>

    <%= f.label :current_manager, :class => 'form-label' %>
    <%= f.text_field :current_manager, :class => 'form-control-sm me-4' %>

    <%= f.submit :class => 'btn btn-primary ' %>
    </div>

<% end%>

</div>

app/views/clubs/edit.html.erb
<h1>Edit Club</h1> <%= link_to "Add Club", new_club_path %>

    <% @clubs.each do |club|%>
<ul>
    <li> <%= link_to club.name, editclub_club_path(club.id) %> </li>
</ul>

<% end%>

app/views/clubs/editclub.html.erb
<div class="p-5">
<h1> Edit <span class='text-primary'><%= @club.name %>'s</span> details </h1>

<%= render :partial => 'form' %>

<%= link_to "Delete Club", @club, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger mt-5 ms-5' %>

</div>

app/views/clubs/index.html.erb
<div class='p-5'>

    <div  class='d-flex align-items-center mb-3'>
        <h1 class=''>Premier League Clubs</h1>
        <% if @current_user.present? && @current_user.admin? %>
        <%= link_to "Add Club", new_club_path, :class => 'btn btn-primary ms-4' %>
        <% end%>
    </div>

     
    <div>
        <% @clubs.each do |club|%>
        <ul>
            <li class='mb-2'> <%= link_to club.name, club_path(club.id), :class => 'text-decoration-none' %> </li>
        </ul>
        <% end%>
    </div>
</div>

app/views/clubs/new.html.erb
<div class="p-5">
<h1>Add <span class='text-primary'> New  </span> Club</h1>

<%= render :partial => 'form' %>
</div>

app/views/clubs/show.html.erb
<div class='d-flex align-items-center'>
    <h1 class='m-4' > <strong> <%= @club.name %> </strong> </h1>
    <% if @current_user.present? && @current_user.admin? %>
    <%= link_to "Edit Club", editclub_club_path(@club.id), :class => 'btn btn-primary ms-4'   %>
    <% end%>
</div>


<h4 class='ms-4'> <%= @club.location %> </h4>

<ul class='list-unstyled ms-4'>
    <li>Current Manager: <%= @club.current_manager %>  </li>
    <li>Titles Won: <%= @club.titles_won %>  </li>
    <li>Stadium Capacity: <%= number_with_delimiter(@club.stadium_cap) %>  </li>
</ul>


<div class='d-flex align-items-center mt-5'>
    <h4 class='ms-4' >Current Squad</h4> 
    <% if @current_user.present? && @current_user.admin? %>
    <%= link_to 'Add Player', new_player_path, :class => 'btn btn-primary ms-4' %>
    <% end%>
</div>

<ul>
    <% @players.each do |player| %>
    <li> <%= link_to player.name, player_path(player), :class => 'text-decoration-none' %>  </li> 
    <% end%>
</ul>
 
<div class = 'd-flex justify-content-center '>
    <%= image_tag @club.logo , :class => 'img-fluid mx-auto logo_club_national' if @club.logo.present? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PremierleagueApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-5 rounded-bottom">
    <div class="container-fluid">
      <h2 class="navbar-brand">OneFootball.com</h2 >
      <% if @current_user.present? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Premier League Clubs", clubs_path, :class => "nav-link active"	 %> 
        </li>
        <li class="nav-item">
        <%= link_to "National Teams", national_teams_path, :class => "nav-link active" %> 
        </li>

        <% if @current_user.present? && @current_user.admin? %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            More...
          </a>

          <ul class="dropdown-menu">
          <li> <%= link_to "List of all PL Player", players_path, :class => 'dropdown-item' %> </li>
          </ul>
          
        <% end%>

        </li>

        <li class='nav-item'>
        <% if @current_user.present?%>
          <%= link_to "Log out #{ @current_user.email }" , login_path, :method => :delete, :class => "nav-link"	 %>
          <% end %>
        </li>
        <% end%>
      </div>
    </div>
  </nav>
    
  <div class='container parent-container'>
    
    <%= yield %>
   
  </div>
  
  
  
  
  
  </body>
</html>

app/views/national_teams/_form.html.erb
<div class="p-5">
<%= form_for @national_team do |f| %>
    <div class="mb-3">
    <%= f.label :name, :class => 'form-label' %>
    <%= f.text_field :name, :class => 'form-control mb-4', :required => true %>

    <%= f.label :coach, :class => 'form-label'  %>
    <%= f.text_field :coach, :class => 'form-control'  %>
    </div>

    <%= f.label :logo, :class => 'form-label'  %>
    <%= f.url_field :logo, :class => 'form-control mb-4'  %>

    <%= f.label :cups_won, "Fifa Ranking", :class => 'form-label' %>
    <%= f.text_field :cups_won, :class => 'form-control-sm'  %>

    <%= f.submit :class => 'btn btn-primary ms-5' %>

<% end%>
</div>

app/views/national_teams/edit.html.erb
<h1>Edit National Teams</h1> <%= link_to "Add New Team", new_national_team_path %>

<ul>
  <% @national_teams.each do |national_team| %>
    <li><%= link_to national_team.name, edit_national_team_path(national_team.id) %></li>

  <% end %>
</ul>

 <%# editclub_club_path(club.id) %>

app/views/national_teams/editteam.html.erb
<div>
<h1 class='p-5'> Edit <span class='text-primary'> <%= @national_team.name %>'s </span> details </h1>

<%= render :partial => 'form' %>

<%= link_to "Delete Team", @national_team, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger mt-5 ms-5 ' %>
</div>

app/views/national_teams/index.html.erb
<div class='p-5'>
  
  <div class='d-flex align-items-center mb-3'>
  <h1>National Teams</h1>
    <% if @current_user.present? && @current_user.admin? %>
    <%= link_to "Add New Team", new_national_team_path, :class => 'btn btn-primary ms-4' %>
    <% end%>
  </div>

  <div>
    <ul>
      <% @national_teams.each do |national_team| %>
        <li class='mb-2'><%= link_to national_team.name, national_team_path(national_team), :class => 'text-decoration-none' %></li>
      <% end %>
    </ul>
  </div>

</div>

app/views/national_teams/new.html.erb
<div class='p-5'>

<h1>Add <span class='text-primary'> New  </span>National Team</h1>

<%= render :partial => 'form' %>
</div>

app/views/national_teams/show.html.erb
<div class='p-4'>

    <div class="d-flex align-items-center mb-3">
        <h1> <strong> <%= @national_team.name %> </strong> </h1>
        <% if @current_user.present? && @current_user.admin? %>
           <%= link_to "Edit National Team", edit_national_team_path(@national_team.id), :class => 'btn btn-primary ms-4'  %> 
        <% end%>
    </div>


    <ul class='list-unstyled ms-4'>
        <li> Coach: <%= @national_team.coach %>  </li>
        <li> Fifa Ranking: <%= @national_team.cups_won.ordinalize %> </li>
    </ul>

    <div class='d-flex align-items-center mt-5 mb-3'>
        <h4 class='ms-4'>Current Squad</h4>
        <% if @current_user.present? && @current_user.admin? %>
            <%= link_to 'Add Player', new_player_path, :class => 'btn btn-primary ms-4' %>
        <% end %>
    </div>

    <% if @players.present?  %>
    <ul>
        <% @players.each do |player| %> 
        <li> <%= link_to player.name, player_path(player.id), :class => 'text-decoration-none' %></li>
         <% end %>
    </ul>
    <% end%>

    <div class = 'd-flex justify-content-center '>
    <%= image_tag @national_team.logo, :class => 'img-fluid mx-auto logo_club_national ' if @national_team.logo.present?  %>
    </div>
</div>

app/views/pages/home.html.erb
<%# Sign up or sign in page %>
<div class=' container-sm p-5 '>

<h1 class='mb-5 '>OneFootball.com</h1>

    <div class='d-flex justify-content-center p-5 border border-white shadow'>

    <h4><%= link_to "Sign Up!", new_user_path, :class => 'btn btn-success ps-4 pe-4 shadow-sm' %> <span class='h5 m-5 '> Or </span></h4>

    <h4><%= link_to "Sign In!",  login_path, :class => 'btn btn-primary ps-4 pe-4' %> </h4>

    </div>

</div>

app/views/pages/show.html.erb
<h1>Work in progress</h1>

app/views/players/_form.html.erb
<div class='mt-4 p-5'>
<%= form_for @player do |f| %>

    <div class="mb-3">
     <%= f.label :name, :class => 'form-label' %>
    <%= f.text_field :name, :class =>"form-control mb-5", :required => true %>
    </div>

    <div class="mb-3">
    <%= f.label :position, :class => 'form-label' %>
    <%= f.text_field :position, :class =>"form-control-sm me-5" %>

    
    <%= f.label :career_goals, 'Club goals', :class => 'form-label' %>
    <%= f.text_field :career_goals, :class =>"form-control-sm me-5" %>
    
    
    <%= f.label :appearances, :class => 'form-label' %>
    <%= f.text_field :appearances, :class =>"form-control-sm me-5" %>
        
    <%= f.label :dob, :class => 'form-label' %>
    <%= f.text_field :dob, :placeholder => 'YYYY-MM-DD', :class =>"form-control-sm" %>
    </div>
        
    <div class="mb-3">
    <%= f.label :image, :class => 'form-label' %>
    <%= f.url_field :image, :class =>"form-control mb-5" %>
    </div>

    
    <%= f.label :club_id, :class => 'form-label'%>
    <%= f.select :club_id, Club.order(:name).pluck(:name, :id), { include_blank: true }, { :class => "form-control-sm", :required => true } %>


    <%= f.label :national_team_id, :class => 'form-label ms-4' %>
    <%= f.select :national_team_id, NationalTeam.order(:name).pluck(:name, :id), {:include_blank => true }, { :class =>"form-control-sm"}%>

   
    <%= f.submit :class => 'btn btn-primary ms-4'  %>
    
<% end%>

</div>
  
  

app/views/players/edit.html.erb
<div class='p-5'>
    <h1>Edit <span class='text-primary'><%= @player.name %>'s</span> details</h1>

    <%= render :partial => 'form' %>

    <div>
        <%= link_to "Delete Player", @player, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger mt-5 ms-4' %>
    </div>
</div>

app/views/players/index.html.erb
<div class="p-3">
  <div class='d-flex align-items-center'>
    <h1>Add or Edit players</h1> 
    <%= link_to "Add New Player", new_player_path, :class => 'btn btn-primary  ms-3' %>
  </div>

    <ul>
      <% @players.each do |player| %>
        <li class='mb-2'>
        <%= link_to player.name,  edit_player_path(player.id) %> playing for <%= player.club.name %>
          <% if player.national_team.present? %>
            and <%= player.national_team.name %>
          <% else %>

          <% end %>
        </li>
      <% end %>
    </ul>
</div>

app/views/players/new.html.erb
<div class="p-4">
    <h1>Add <span class='text-primary'> New </span>Player</h1>
    <%= render :partial => 'form' %>
</div>

app/views/players/show.html.erb
<div class = 'player-show-card'>
  
  <div class="card mt-4 border border--dark-subtle shadow-lg" style="width: 22rem;">
    <%= image_tag @player.image, :class =>  'card-img-top' if @player.image.present? %>

    <div class="card-body">
      <h4 class="card-title  mb-5"><%= @player.name %></h4>

      <ul class="list-group list-group-flush">

      <li class="list-group-item">Position: <%=@player.position %></li>
      <li class="list-group-item">Club Appearances: <%= @player.appearances %></li>
      <li class="list-group-item">D.O.B: <%= @player.dob.strftime('%B %e, %Y') if @player.dob? %></li>
      <li class="list-group-item">Club goals:  <%= @player.career_goals %></li>

      <li class="list-group-item">Current club: <%= link_to @player.club.name, club_path(@player.club_id) %></li>
      <% if @nationalteam.present?  %>
      <li class="list-group-item">National Team: <%= link_to @nationalteam.name, national_team_path(@nationalteam.id) %> </li>
      <% end %>
 
      </ul>
      <% if @current_user.present? && @current_user.admin? %>
      <%= link_to "Edit Player",edit_player_path(@player.id), :class => 'btn btn-primary ms-4 mt-4' %>
      <% end%>
      </div>
  </div>

</div>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<div class='p-5'>

    <h1>Sign in</h1>

    <% if flash[:error].present?%>
    <h2>
        <%= flash[:error] %>
    </h2>
    <% end%>

    <div class='d-flex align-items-center justify-content-center p-5'>
        <%= form_tag login_path do %>
        <div class='d-flex align-items-center mb-4'>
            <%= label_tag :email, 'Email:', :class => 'form-label me-5' %>
            <%= email_field_tag :email,nil, :class => 'form-control-lg' %>
        </div>
    
        <div class='d-flex align-items-center'>
            <%= label_tag :password, 'Password:', :class => 'form-label me-3' %>
            <%= password_field_tag :password, nil, :class => 'form-control-lg' %>
        </div>

        <div class='d-flex justify-content-center mt-4'>
            <%= submit_tag "Sign In", :class => 'btn btn-primary' %>
        </div>
        <% end%>

    </div>
</div>

app/views/users/index.html.erb
<h1>Welcome Page</h1>

    <% @users.each do |user| %>
        <p> <%= user.email %> </p>
    <% end%>

app/views/users/new.html.erb
<div class="p-5">
<h1 class='mb-3'>Sign up!</h1>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>
<div class='p-5'>
<%= form_for @user do |f| %>
    
    <%= f.label :email, :class => 'form-label' %>
    <%= f.email_field :email, :class => 'form-control' %>
    <%= f.label :password, :class => 'form-label' %>
    <%= f.password_field :password, :class => 'form-control' %>
    <%= f.label :password_confirmation, :class => 'form-label' %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>
    <%= f.submit "Sign up!", :class => 'btn btn-success btn-lg mt-4' %>
    
<% end %>

</div>
</div>